// Home-level action type (used for loading-level reducer)

export enum HomeActionType {
	RETRIEVE_TRENDING_ARTICLES = "RETRIEVE_TRENDING_ARTICLES",
	RETRIEVE_MOST_CLAPPED_ARTICLES = "RETRIEVE_MOST_CLAPPED_ARTICLES",
	RETRIEVE_RECENTLY_RELEASED_ARTICLES = "RETRIEVE_RECENTLY_RELEASED_ARTICLES"
}

// Home-level action state type (used for home-level reducer and actions)

export enum HomeActionStateType {
	RETRIEVE_TRENDING_ARTICLES_REQUEST = "RETRIEVE_TRENDING_ARTICLES_REQUEST",
	RETRIEVE_TRENDING_ARTICLES_SUCCESS = "RETRIEVE_TRENDING_ARTICLES_SUCCESS",
	RETRIEVE_TRENDING_ARTICLES_FAILURE = "RETRIEVE_TRENDING_ARTICLES_FAILURE",
	RETRIEVE_MOST_CLAPPED_ARTICLES_REQUEST = "RETRIEVE_MOST_CLAPPED_ARTICLES_REQUEST",
	RETRIEVE_MOST_CLAPPED_ARTICLES_SUCCESS = "RETRIEVE_MOST_CLAPPED_ARTICLES_SUCCESS",
	RETRIEVE_MOST_CLAPPED_ARTICLES_FAILURE = "RETRIEVE_MOST_CLAPPED_ARTICLES_FAILURE",
	RETRIEVE_RECENTLY_RELEASED_ARTICLES_REQUEST = "RETRIEVE_RECENTLY_RELEASED_ARTICLES_REQUEST",
	RETRIEVE_RECENTLY_RELEASED_ARTICLES_SUCCESS = "RETRIEVE_RECENTLY_RELEASED_ARTICLES_SUCCESS",
	RETRIEVE_RECENTLY_RELEASED_ARTICLES_FAILURE = "RETRIEVE_RECENTLY_RELEASED_ARTICLES_FAILURE"
}
